# pyproject.toml
[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "tsqc"
dynamic = ["version"]

authors = [
    {name = "Daan Starre", email = "daan.starre@example.com"}
]

classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

# OPTIONEEL MAAR AANBEVOLEN: Definieer een commando voor de runner
[project.scripts]
tsqc = "tsqc.runner:main"

[tool.maturin]
# Vertel maturin expliciet hoe de native module moet heten.
module-name = "tsqc._native"

# DIT IS DE CRUCIALE FIX: Vertel maturin waar de Python-broncode staat.
python-source = "src"

features = ["pyo3/extension-module", "parallel_mcts"]