# pyproject.toml
[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "tsqc"
requires-python = ">=3.8"

# CORRECTIE: Vertel maturin dat de versie dynamisch is en uit Cargo.toml komt.
dynamic = ["version"]

authors = [
    {name = "Daan Starre", email = "daan.starre@example.com"}
]

classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[tool.maturin]
features = ["pyo3/extension-module", "parallel_mcts"]