# pyproject.toml
[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "tsqc"
dynamic = ["version"]

authors = [
    {name = "Daan Starre", email = "daan.starre@example.com"}
]

classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[tool.maturin]
# CORRECTIE: Vertel maturin expliciet hoe de native module moet heten.
# Dit lost de 'PyInit_tsqc' waarschuwing op.
module-name = "tsqc._native"
features = ["pyo3/extension-module", "parallel_mcts"]